export function embedJsonInHTML(json, withMagic) {
    // const json = JSON.stringify(data);

    let magic = '';
    if (withMagic) {
      magic = '%%HTML';
    }

    const textContent = `
    ${magic}
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Static Template</title>
        <style>
          body {
            font-family: Arial, sans-serif;
          }
          .question {
            font-weight: bold;
          }
          .options {
            margin: 10px 0;
          }
          .option {
            display: block;
            margin: 5px 0;
          }
          .option input {
            margin-right: 5px;
          }
          .button-container {
            margin: 10px 0;
          }
        </style>
      </head>
      <body>
    
          <h1>
              Test quiz generated by quizBuilder
            <h2>
    
        <div class="question"></div>
        <div class="options"></div>
        <div class="button-container">
          <button onclick="nextQuestion()">Next</button>
        </div>
    
    
    
        <script>
          const questions = ${json};
    
          let currentQuestionIndex = 0;
    
          function renderQuestion() {
            const question = questions[currentQuestionIndex];
            document.querySelector(".question").textContent = question.question;
            const optionsDiv = document.querySelector(".options");
            optionsDiv.innerHTML = "";
            for (let i = 1; i <= 4; i++) {
              const optionDiv = document.createElement("div");
              optionDiv.className = "option";
              const input = document.createElement("input");
              input.type = "checkbox";
              input.id = \`answer\${i}\`;
              const label = document.createElement("label");
              label.htmlFor = \`answer\${i}\`;
              label.textContent = question[\`answer\${i}\`];
              optionDiv.appendChild(input);
              optionDiv.appendChild(label);
              optionsDiv.appendChild(optionDiv);
            }
          }
    
          function nextQuestion() {
            if (currentQuestionIndex < questions.length - 1) {
              currentQuestionIndex++;
              renderQuestion();
            } else {
              alert("Quiz completed!");
            }
          }
    
          renderQuestion();
        </script>
      </body>
    </html>
    `;
    return textContent;

}